// Defines the global `Pulsar` bridge before any test module is imported, so modules that
// read `Pulsar.exportConfig()` at load time (e.g. src/index.ts) work under Jest.
const config = {
  showGeneratedFileDisclaimer: true,
  disclaimer: "Generated by Supernova.io.",
  showDescriptions: true,
  generateEmptyFiles: false,
  useReferences: true,
  tokenNameStyle: "camelCase",
  tokenNameStructure: "pathAndName",
  globalNamePrefix: "",
  customizeTokenPrefixes: false,
  tokenPrefixes: {},
  numericPrecision: 2,
  indent: 4,
  baseStyleFilePath: "./Styles",
  exportThemesAs: "separateFiles",
  exportBaseValues: true,
  exportOnlyThemedTokens: false,
  darkThemeName: "dark",
  colorAssetCatalogName: "Colors.xcassets",
  semanticGroupName: "semantic",
}

;(globalThis as unknown as { Pulsar: unknown }).Pulsar = {
  exportConfig: () => config,
  export: () => undefined,
}
